// FORGE exercise library — 150+ fully-tagged movements.
// Canonical storage of metadata that powers search, the swap engine, and the
// back-safety filter. Every entry is keyed by a stable slug for idempotent seeding.

// isBackSafe defaults to: spinalLoad in (NONE, LOW) AND pattern !== HINGE.
// Pass isBackSafe explicitly to override (e.g. hip thrusts: hinge but back-supported = safe).
function mk(o) {
  const spinalLoad = o.spinalLoad ?? 'NONE';
  const derived =
    ['NONE', 'LOW'].includes(spinalLoad) && o.movementPattern !== 'HINGE';
  return {
    unilateral: false,
    secondaryMuscles: [],
    equipment: [],
    tempoNote: null,
    videoUrl: null,
    cues: null,
    defaultRepRange: null,
    ...o,
    spinalLoad,
    isBackSafe: o.isBackSafe ?? derived,
  };
}

const exercises = [
  // ============================== QUADS ==============================
  mk({ slug: 'back-squat', name: 'Barbell Back Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'ABS'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '5-8', cues: 'Brace hard, knees track over toes, hit depth without losing the arch.' }),
  mk({ slug: 'front-squat', name: 'Barbell Front Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'ABS'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '6-8', cues: 'Tall chest, elbows high, stay upright as you descend.' }),
  mk({ slug: 'smith-machine-squat', name: 'Smith Machine Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'HAMSTRINGS'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['SMITH_MACHINE'], spinalLoad: 'MODERATE', defaultRepRange: '5-8', cues: 'Set feet slightly forward, controlled descent, drive the bar straight up.' }),
  mk({ slug: 'smith-front-squat', name: 'Smith Front Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'ABS'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['SMITH_MACHINE'], spinalLoad: 'MODERATE', defaultRepRange: '6-8', cues: 'Front-rack the bar, stay vertical, smooth tempo.' }),
  mk({ slug: 'hack-squat', name: 'Hack Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Back flat on the pad, full depth, push through mid-foot.' }),
  mk({ slug: 'goblet-squat', name: 'Goblet Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'ABS'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['DUMBBELL', 'KETTLEBELL'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Hold the bell at the chest, elbows inside knees at the bottom.' }),
  mk({ slug: 'heel-elevated-squat', name: 'Heel-Elevated Goblet Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Heels on a wedge to bias the quads; stay upright.' }),
  mk({ slug: 'leg-press', name: 'Leg Press', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'HAMSTRINGS'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Low back stays glued to the seat; don’t let the knees collapse in.' }),
  mk({ slug: 'single-leg-leg-press', name: 'Single-Leg Leg Press', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['MACHINE'], unilateral: true, spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Control the eccentric; full range each leg.' }),
  mk({ slug: 'bulgarian-split-squat', name: 'DB Bulgarian Split Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'HAMSTRINGS'], movementPattern: 'LUNGE', category: 'COMPOUND', equipment: ['DUMBBELL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Rear foot elevated, drop straight down, drive through the front heel.' }),
  mk({ slug: 'walking-lunge', name: 'DB Walking Lunge', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES', 'HAMSTRINGS'], movementPattern: 'LUNGE', category: 'COMPOUND', equipment: ['DUMBBELL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-20', cues: 'Long stride, knee kisses the floor, stay tall.' }),
  mk({ slug: 'reverse-lunge', name: 'DB Reverse Lunge', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'LUNGE', category: 'COMPOUND', equipment: ['DUMBBELL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Step back under control; easier on the knees than forward lunges.' }),
  mk({ slug: 'smith-reverse-lunge', name: 'Smith Reverse Lunge', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'LUNGE', category: 'COMPOUND', equipment: ['SMITH_MACHINE'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '12-15', cues: 'Bar on traps, step back, controlled stable reps.' }),
  mk({ slug: 'step-up', name: 'DB Step-Up', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'LUNGE', category: 'COMPOUND', equipment: ['DUMBBELL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-12', cues: 'Drive through the top foot; minimal push off the bottom leg.' }),
  mk({ slug: 'sissy-squat', name: 'Sissy Squat', primaryMuscle: 'QUADS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Knees travel forward, lean back, feel a deep quad stretch.' }),
  mk({ slug: 'leg-extension', name: 'Leg Extension', primaryMuscle: 'QUADS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Squeeze hard at the top, slow negative.' }),
  mk({ slug: 'cable-leg-extension', name: 'Cable Leg Extension', primaryMuscle: 'QUADS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Ankle strap on the low pulley; full lockout, controlled return.' }),
  mk({ slug: 'reverse-nordic', name: 'Reverse Nordic', primaryMuscle: 'QUADS', secondaryMuscles: ['ABS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Tall kneel, lean back from the knees with a long stretch.' }),

  // ============================ HAMSTRINGS ============================
  mk({ slug: 'deadlift', name: 'Conventional Deadlift', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES', 'UPPER_BACK', 'TRAPS', 'LATS'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '3-6', cues: 'Brace, push the floor away, bar stays against the legs.' }),
  mk({ slug: 'romanian-deadlift', name: 'Romanian Deadlift', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES', 'UPPER_BACK'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '6-10', cues: 'Soft knees, hips back, feel the stretch, neutral spine throughout.' }),
  mk({ slug: 'stiff-leg-deadlift', name: 'Stiff-Leg Deadlift', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '8-10', cues: 'Minimal knee bend; maximal hamstring stretch.' }),
  mk({ slug: 'dumbbell-rdl', name: 'Dumbbell RDL', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['DUMBBELL'], spinalLoad: 'HIGH', defaultRepRange: '8-12', cues: 'Dumbbells skim the thighs; hinge, don’t squat.' }),
  mk({ slug: 'good-morning', name: 'Good Morning', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '8-12', cues: 'Light load, hinge with a flat back, feel the hamstrings.' }),
  mk({ slug: 'lying-leg-curl', name: 'Lying Leg Curl', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['CALVES'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Curl all the way, hips down on the pad, slow eccentric.' }),
  mk({ slug: 'seated-leg-curl', name: 'Seated Leg Curl', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['CALVES'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Drive the pad down and under; great stretch position.' }),
  mk({ slug: 'slider-leg-curl', name: 'Slider Leg Curl', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['SLIDER', 'BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Bridge up, slide heels out and curl back without dropping the hips.' }),
  mk({ slug: 'swiss-ball-leg-curl', name: 'Swiss-Ball Leg Curl', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['SWISS_BALL', 'BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '12-15', cues: 'Heels on the ball, hips high, curl the ball to your glutes.' }),
  mk({ slug: 'single-leg-slider-curl', name: 'Single-Leg Slider Leg Curl', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['SLIDER', 'SWISS_BALL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'One leg at a time; resist the slide on the way out.' }),
  mk({ slug: 'nordic-curl', name: 'Nordic Curl', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '5-10', cues: 'Anchor the ankles, lower as slowly as possible, catch and push back.' }),
  mk({ slug: 'cable-pull-through', name: 'Cable Pull-Through', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '12-20', cues: 'Rope between the legs, hinge back then snap the hips through.' }),
  mk({ slug: 'glute-ham-raise', name: 'Glute-Ham Raise', primaryMuscle: 'HAMSTRINGS', secondaryMuscles: ['GLUTES', 'CALVES'], movementPattern: 'ISOLATION', category: 'COMPOUND', equipment: ['MACHINE', 'BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Lower under control, pull yourself back with the hamstrings.' }),

  // ============================== GLUTES ==============================
  mk({ slug: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS', 'QUADS'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '6-12', cues: 'Chin tucked, ribs down, full lockout, pause and squeeze the glutes.' }),
  mk({ slug: 'smith-machine-hip-thrust', name: 'Smith Machine Hip Thrust', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['SMITH_MACHINE', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '6-12', cues: 'Stable bar path; lock out hard and pause at the top.' }),
  mk({ slug: 'dumbbell-hip-thrust', name: 'DB Hip Thrust', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-15', cues: 'Dumbbell across the hips; full lockout each rep.' }),
  mk({ slug: 'single-leg-hip-thrust', name: 'Single-Leg Hip Thrust', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BODYWEIGHT', 'BENCH'], unilateral: true, spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-15', cues: 'Drive through one heel; keep hips level.' }),
  mk({ slug: 'glute-bridge', name: 'Glute Bridge', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['BARBELL', 'BODYWEIGHT'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '12-20', cues: 'Floor-based; posterior pelvic tilt, squeeze at the top.' }),
  mk({ slug: 'cable-glute-kickback', name: 'Cable Glute Kickback', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], unilateral: true, spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Ankle strap; kick straight back, squeeze, no lower-back arch.' }),
  mk({ slug: 'machine-glute-kickback', name: 'Machine Glute Kickback', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], unilateral: true, spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Controlled extension, pause at peak contraction.' }),
  mk({ slug: 'hip-abduction', name: 'Hip Abduction Machine', primaryMuscle: 'GLUTES', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '15-25', cues: 'Lean forward slightly to bias the glute med; slow and controlled.' }),
  mk({ slug: 'lateral-band-walk', name: 'Lateral Band Walk', primaryMuscle: 'GLUTES', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BAND'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Band above knees, athletic stance, push out and step sideways.' }),

  // ============================== CALVES ==============================
  mk({ slug: 'standing-calf-raise', name: 'Standing Calf Raise', primaryMuscle: 'CALVES', secondaryMuscles: [], movementPattern: 'CALF_RAISE', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'LOW', defaultRepRange: '8-15', cues: 'Full stretch at the bottom, explosive up, pause at the top.' }),
  mk({ slug: 'smith-standing-calf-raise', name: 'Smith Standing Calf Raise', primaryMuscle: 'CALVES', secondaryMuscles: [], movementPattern: 'CALF_RAISE', category: 'ISOLATION', equipment: ['SMITH_MACHINE'], spinalLoad: 'LOW', defaultRepRange: '8-15', cues: 'Toes on a plate, deep stretch, big squeeze at the top.' }),
  mk({ slug: 'dumbbell-standing-calf-raise', name: 'DB Standing Calf Raise', primaryMuscle: 'CALVES', secondaryMuscles: [], movementPattern: 'CALF_RAISE', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'One or two dumbbells; full range, no bouncing.' }),
  mk({ slug: 'seated-calf-raise', name: 'Seated Calf Raise', primaryMuscle: 'CALVES', secondaryMuscles: [], movementPattern: 'CALF_RAISE', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Bias the soleus; slow tempo, full stretch.' }),
  mk({ slug: 'leg-press-calf-raise', name: 'Leg Press Calf Raise', primaryMuscle: 'CALVES', secondaryMuscles: [], movementPattern: 'CALF_RAISE', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Toes on the platform edge; press through the balls of the feet.' }),
  mk({ slug: 'single-leg-calf-raise', name: 'Single-Leg Calf Raise', primaryMuscle: 'CALVES', secondaryMuscles: [], movementPattern: 'CALF_RAISE', category: 'ISOLATION', equipment: ['DUMBBELL', 'BODYWEIGHT'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'One leg, full stretch and contraction; hold a DB for load.' }),

  // ============================== CHEST ==============================
  mk({ slug: 'barbell-bench-press', name: 'Barbell Bench Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '4-8', cues: 'Shoulder blades pinned, slight arch, bar to mid-chest, leg drive.' }),
  mk({ slug: 'incline-barbell-bench-press', name: 'Incline Barbell Bench Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '6-10', cues: '30° bench, bar to upper chest, elbows tucked ~45°.' }),
  mk({ slug: 'decline-barbell-bench-press', name: 'Decline Barbell Bench Press', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '6-10', cues: 'Lower-chest bias; bar to the sternum.' }),
  mk({ slug: 'flat-dumbbell-press', name: 'Flat Dumbbell Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Deep stretch at the bottom, press and slightly together at the top.' }),
  mk({ slug: 'incline-dumbbell-press', name: 'DB Incline Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Upper-chest focus; control the stretch, don’t clank the dumbbells.' }),
  mk({ slug: 'decline-dumbbell-press', name: 'Decline Dumbbell Press', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Lower-chest bias; full range.' }),
  mk({ slug: 'smith-bench-press', name: 'Smith Bench Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['SMITH_MACHINE', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '6-10', cues: 'Fixed bar path; great for pushing close to failure solo.' }),
  mk({ slug: 'machine-chest-press', name: 'Machine Chest Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '8-12', cues: 'Handles at mid-chest height; squeeze the pecs at lockout.' }),
  mk({ slug: 'dip', name: 'Weighted Dip', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BODYWEIGHT', 'PULL_UP_BAR'], spinalLoad: 'NONE', defaultRepRange: '6-12', cues: 'Lean forward for chest; controlled depth, no shrugging.' }),
  mk({ slug: 'push-up', name: 'Push-Up', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS', 'FRONT_DELTS', 'ABS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '10-20', cues: 'Rigid plank, elbows ~45°, full lockout.' }),
  mk({ slug: 'low-to-high-cable-flye', name: 'Low-to-High Cable Flye', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Pulleys low, sweep up and in like an uppercut; squeeze.' }),
  mk({ slug: 'cable-flye', name: 'Cable Flye', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Mid-height pulleys; soft elbows, big stretch and squeeze.' }),
  mk({ slug: 'high-to-low-cable-flye', name: 'High-to-Low Cable Flye', primaryMuscle: 'CHEST', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Pulleys high; drive hands down and together for the lower chest.' }),
  mk({ slug: 'pec-deck', name: 'Pec Deck', primaryMuscle: 'CHEST', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Elbows slightly below shoulders; squeeze and hold.' }),
  mk({ slug: 'dumbbell-flye', name: 'Dumbbell Flye', primaryMuscle: 'CHEST', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Big arc, soft elbows, stretch then hug.' }),
  mk({ slug: 'floor-press', name: 'Floor Press', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'NONE', defaultRepRange: '6-10', cues: 'Triceps touch the floor, pause, press; shoulder-friendly.' }),
  mk({ slug: 'db-floor-press', name: 'DB Floor Press', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL'], spinalLoad: 'NONE', defaultRepRange: '8-12', cues: 'Elbows lightly touch the floor each rep; great solo dip fallback.' }),

  // ============================ LATS / BACK (vertical pull) ============================
  mk({ slug: 'pull-up', name: 'Pull-Up', primaryMuscle: 'LATS', secondaryMuscles: ['UPPER_BACK', 'BICEPS', 'FOREARMS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['PULL_UP_BAR', 'BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '5-10', cues: 'Pull the elbows to the ribs, chest to bar, control the descent.' }),
  mk({ slug: 'chin-up', name: 'Chin-Up', primaryMuscle: 'LATS', secondaryMuscles: ['BICEPS', 'UPPER_BACK'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['PULL_UP_BAR', 'BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '6-10', cues: 'Supinated grip; more biceps, full range.' }),
  mk({ slug: 'lat-pulldown', name: 'Wide-Grip Lat Pulldown', primaryMuscle: 'LATS', secondaryMuscles: ['UPPER_BACK', 'BICEPS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['CABLE', 'MACHINE'], spinalLoad: 'LOW', defaultRepRange: '8-15', cues: 'Drive elbows down and back; minimal lean, no swinging.' }),
  mk({ slug: 'neutral-grip-pulldown', name: 'Neutral-Grip Cable Pulldown', primaryMuscle: 'LATS', secondaryMuscles: ['UPPER_BACK', 'BICEPS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Neutral handle, pull to the upper chest, big lat squeeze.' }),
  mk({ slug: 'supinated-pulldown', name: 'Supinated Lat Pulldown', primaryMuscle: 'LATS', secondaryMuscles: ['BICEPS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Underhand, elbows tight to the body.' }),
  mk({ slug: 'single-arm-pulldown', name: 'Single-Arm Cable Pulldown', primaryMuscle: 'LATS', secondaryMuscles: ['BICEPS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Long stretch overhead, pull to the hip, full lat contraction.' }),
  mk({ slug: 'one-arm-cable-lat-pull-in', name: '1-Arm Cable Lat Pull-In', primaryMuscle: 'LATS', secondaryMuscles: ['UPPER_BACK'], movementPattern: 'VERTICAL_PULL', category: 'ISOLATION', equipment: ['CABLE'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '15-20', cues: 'High pulley; pull the elbow down to the hip, pure lat isolation.' }),
  mk({ slug: 'straight-arm-pulldown', name: 'Straight-Arm Cable Pull-Over', primaryMuscle: 'LATS', secondaryMuscles: ['TRICEPS', 'ABS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '12-20', cues: 'Stiff arms, sweep the bar from overhead to the thighs; feel the lats.' }),
  mk({ slug: 'kneeling-straight-arm-pulldown', name: 'Kneeling Straight-Arm Cable Pull-Over', primaryMuscle: 'LATS', secondaryMuscles: ['TRICEPS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '12-20', cues: 'Kneel for a longer stretch; control the eccentric.' }),
  mk({ slug: 'dumbbell-pullover', name: 'Dumbbell Pull-Over', primaryMuscle: 'LATS', secondaryMuscles: ['CHEST', 'TRICEPS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Big stretch behind the head, pull back over the chest.' }),
  mk({ slug: 'cable-high-row', name: 'Cable High Row', primaryMuscle: 'LATS', secondaryMuscles: ['UPPER_BACK', 'REAR_DELTS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-15', cues: 'Seated, pull a high anchor down to the upper abs; squeeze the lats.' }),
  mk({ slug: 'machine-high-row', name: 'Machine High Row', primaryMuscle: 'LATS', secondaryMuscles: ['UPPER_BACK'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-15', cues: 'Chest on the pad; drive elbows down and back.' }),

  // ============================ UPPER / MID BACK ============================
  mk({ slug: 'barbell-row', name: 'Barbell Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'REAR_DELTS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '6-10', cues: 'Hinge ~45°, flat back, row to the lower ribs.' }),
  mk({ slug: 'pendlay-row', name: 'Pendlay Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'HIGH', defaultRepRange: '5-8', cues: 'Dead-stop each rep from the floor; explosive pull, flat back.' }),
  mk({ slug: 'dumbbell-one-arm-row', name: 'DB One-Arm Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], unilateral: true, spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '8-12', cues: 'Brace on the bench; row to the hip, no torso rotation.' }),
  mk({ slug: 'chest-supported-dumbbell-row', name: 'Chest-Supported DB Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'REAR_DELTS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '8-12', cues: 'Chest on an incline bench; row both dumbbells, squeeze the mid-back.' }),
  mk({ slug: 'incline-chest-supported-row', name: 'Incline Chest-Supported Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '10-12', cues: 'High incline; strict tempo, no body english.' }),
  mk({ slug: 'seal-row', name: 'Seal Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '8-12', cues: 'Fully prone on a high bench; pure back, zero momentum.' }),
  mk({ slug: 't-bar-row', name: 'T-Bar Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['BARBELL', 'MACHINE'], spinalLoad: 'MODERATE', defaultRepRange: '8-12', cues: 'Hinge with a flat back; drive elbows past the torso.' }),
  mk({ slug: 'chest-supported-t-bar-row', name: 'Chest-Supported T-Bar Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '8-12', cues: 'Pad-supported; row heavy without loading the spine.' }),
  mk({ slug: 'cable-seated-row', name: 'Cable Seated Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '8-12', cues: 'Tall chest, pull to the navel, no heaving with the lower back.' }),
  mk({ slug: 'cable-seated-row-elbows-out', name: 'Cable Seated Elbows-Out Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['REAR_DELTS', 'TRAPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-12', cues: 'Rope to the throat, elbows flare high; hammers the upper back.' }),
  mk({ slug: 'wide-grip-cable-row', name: 'Wide-Grip Cable Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['REAR_DELTS', 'LATS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-15', cues: 'Wide bar, elbows out; upper-back and rear-delt focus.' }),
  mk({ slug: 'machine-row', name: 'Machine Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '10-12', cues: 'Chest on the pad; full stretch and squeeze.' }),
  mk({ slug: 'single-arm-cable-row', name: 'Single-Arm Cable Row', primaryMuscle: 'UPPER_BACK', secondaryMuscles: ['LATS', 'BICEPS'], movementPattern: 'HORIZONTAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], unilateral: true, spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '8-12', cues: 'Big stretch and rotation; pull to the hip, squeeze the lat.' }),
  mk({ slug: 'face-pull', name: 'Cable Face Pull', primaryMuscle: 'REAR_DELTS', secondaryMuscles: ['UPPER_BACK', 'TRAPS'], movementPattern: 'HORIZONTAL_PULL', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '15-25', cues: 'Rope to the eyes, elbows high, externally rotate at the end.' }),

  // ============================== TRAPS ==============================
  mk({ slug: 'barbell-shrug', name: 'Barbell Shrug', primaryMuscle: 'TRAPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BARBELL'], spinalLoad: 'MODERATE', defaultRepRange: '10-15', cues: 'Straight up to the ears, pause, no rolling.' }),
  mk({ slug: 'dumbbell-shrug', name: 'DB Shrug', primaryMuscle: 'TRAPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '12-20', cues: 'Elevate the shoulders straight up; squeeze and hold.' }),
  mk({ slug: 'cable-shrug', name: 'Cable Shrug', primaryMuscle: 'TRAPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Constant tension from the low pulley; full shrug.' }),
  mk({ slug: 'smith-shrug', name: 'Smith Shrug', primaryMuscle: 'TRAPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['SMITH_MACHINE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '12-20', cues: 'Fixed path lets you overload safely; pause at the top.' }),
  mk({ slug: 'upright-row', name: 'Barbell Upright Row', primaryMuscle: 'TRAPS', secondaryMuscles: ['SIDE_DELTS', 'FOREARMS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Pull to mid-chest, elbows lead; avoid if it pinches the shoulder.' }),
  mk({ slug: 'cable-rope-upright-row', name: 'Cable Rope Upright Row', primaryMuscle: 'TRAPS', secondaryMuscles: ['SIDE_DELTS'], movementPattern: 'VERTICAL_PULL', category: 'COMPOUND', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '15-20', cues: 'Rope from a low pulley; elbows high, smooth pull.' }),

  // ============================== DELTS ==============================
  mk({ slug: 'overhead-press', name: 'Standing Overhead Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['SIDE_DELTS', 'TRICEPS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL'], spinalLoad: 'MODERATE', defaultRepRange: '4-8', cues: 'Tight glutes and abs, bar over the mid-foot, press and shrug at the top.' }),
  mk({ slug: 'seated-barbell-press', name: 'Seated Barbell Overhead Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['TRICEPS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '5-8', cues: 'Upright bench; press without overarching the lower back.' }),
  mk({ slug: 'seated-dumbbell-press', name: 'Seated DB Shoulder Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['SIDE_DELTS', 'TRICEPS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '6-12', cues: 'Supported back; press to a full lockout, controlled negative.' }),
  mk({ slug: 'standing-dumbbell-press', name: 'Standing DB Shoulder Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['TRICEPS', 'ABS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL'], spinalLoad: 'MODERATE', defaultRepRange: '8-12', cues: 'Brace hard; don’t lean back.' }),
  mk({ slug: 'smith-shoulder-press', name: 'Smith Shoulder Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['TRICEPS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['SMITH_MACHINE', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '6-10', cues: 'Seated; fixed path for safe overload.' }),
  mk({ slug: 'machine-shoulder-press', name: 'Machine Shoulder Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['SIDE_DELTS', 'TRICEPS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['MACHINE'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '8-12', cues: 'Press and lockout; great for pushing to failure.' }),
  mk({ slug: 'arnold-press', name: 'Seated DB Arnold Press', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: ['SIDE_DELTS', 'TRICEPS'], movementPattern: 'VERTICAL_PUSH', category: 'COMPOUND', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-12', cues: 'Rotate from palms-in to palms-out as you press; full delt sweep.' }),
  mk({ slug: 'dumbbell-lateral-raise', name: 'DB Lateral Raise', primaryMuscle: 'SIDE_DELTS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Lead with the elbows, pour-out at the top, slow on the way down.' }),
  mk({ slug: 'cable-lateral-raise', name: 'Cable Lateral Raise', primaryMuscle: 'SIDE_DELTS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Cable behind the back; constant tension through the full range.' }),
  mk({ slug: 'machine-lateral-raise', name: 'Machine Lateral Raise', primaryMuscle: 'SIDE_DELTS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Pads against the forearms; drive up and pause.' }),
  mk({ slug: 'band-lateral-raise', name: 'Band Lateral Raise', primaryMuscle: 'SIDE_DELTS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BAND'], spinalLoad: 'NONE', defaultRepRange: '15-25', cues: 'Stand on the band; smooth raises, control the snap-back.' }),
  mk({ slug: 'egyptian-lateral-raise', name: 'Egyptian Cable Lateral Raise', primaryMuscle: 'SIDE_DELTS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], unilateral: true, spinalLoad: 'NONE', defaultRepRange: '12-15', cues: 'Lean away from the stack for a huge range; strict single-arm reps.' }),
  mk({ slug: 'front-raise', name: 'DB Front Raise', primaryMuscle: 'FRONT_DELTS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '12-15', cues: 'Raise to eye level, no swinging.' }),
  mk({ slug: 'rear-delt-flye', name: 'DB Rear-Delt Flye', primaryMuscle: 'REAR_DELTS', secondaryMuscles: ['UPPER_BACK'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'NONE', defaultRepRange: '15-20', cues: 'Hinge or chest-support; sweep out, lead with the pinkies.' }),
  mk({ slug: 'cable-reverse-flye', name: 'Cable Reverse Flye', primaryMuscle: 'REAR_DELTS', secondaryMuscles: ['UPPER_BACK'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '15-20', cues: 'Cross the cables; pull apart and back, constant tension.' }),
  mk({ slug: 'reverse-pec-deck', name: 'Reverse Pec Deck', primaryMuscle: 'REAR_DELTS', secondaryMuscles: ['UPPER_BACK'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '15-20', cues: 'Drive elbows back, squeeze the rear delts.' }),

  // ============================== BICEPS ==============================
  mk({ slug: 'barbell-curl', name: 'Barbell Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BARBELL'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Elbows pinned, no swing, full squeeze.' }),
  mk({ slug: 'ez-bar-curl', name: 'EZ-Bar Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['EZ_BAR'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Angled grip is wrist-friendly; strict reps.' }),
  mk({ slug: 'dumbbell-curl', name: 'DB Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Supinate as you curl; squeeze at the top.' }),
  mk({ slug: 'supinated-dumbbell-curl', name: 'Supinated DB Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '12-15', cues: 'Start supinated and stay there; strict, full contraction.' }),
  mk({ slug: 'pronated-dumbbell-curl', name: 'Pronated DB Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '10-12', cues: 'Overhand grip; targets the brachialis and forearms.' }),
  mk({ slug: 'hammer-curl', name: 'DB Hammer Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Neutral grip; builds the brachialis and forearm.' }),
  mk({ slug: 'reverse-grip-curl', name: 'Reverse-Grip DB Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '15-20', cues: 'Pronated curl; forearm and brachialis emphasis, high reps.' }),
  mk({ slug: 'preacher-curl', name: 'Preacher Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['EZ_BAR', 'MACHINE'], spinalLoad: 'NONE', defaultRepRange: '8-12', cues: 'Arms locked on the pad; control the stretch at the bottom.' }),
  mk({ slug: 'db-preacher-curl', name: 'DB Preacher Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'NONE', defaultRepRange: '10-12', cues: 'One arm at a time on the preacher bench; deep stretch, hard squeeze.' }),
  mk({ slug: 'spider-curl', name: 'DB Spider Curl', primaryMuscle: 'BICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'NONE', defaultRepRange: '12-20', cues: 'Chest on an incline, arms hanging; pure peak-contraction reps.' }),
  mk({ slug: 'incline-dumbbell-curl', name: 'Incline DB Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'NONE', defaultRepRange: '10-12', cues: 'Lean back for a long-head stretch; strict reps.' }),
  mk({ slug: 'cable-curl', name: 'Cable Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Constant tension; squeeze hard at the top.' }),
  mk({ slug: 'single-arm-cable-curl', name: 'Single-Arm Cable Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Cable behind the body for a long-head stretch; strict single-arm.' }),
  mk({ slug: 'concentration-curl', name: 'Concentration Curl', primaryMuscle: 'BICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Elbow braced on the thigh; peak squeeze every rep.' }),

  // ============================== TRICEPS ==============================
  mk({ slug: 'close-grip-bench-press', name: 'Close-Grip Bench Press', primaryMuscle: 'TRICEPS', secondaryMuscles: ['CHEST', 'FRONT_DELTS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BARBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '6-10', cues: 'Shoulder-width grip, elbows tucked, bar to the lower chest.' }),
  mk({ slug: 'close-grip-smith-press', name: 'Close-Grip Smith Press', primaryMuscle: 'TRICEPS', secondaryMuscles: ['CHEST'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['SMITH_MACHINE', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'Fixed path; tuck the elbows and press from the lower chest.' }),
  mk({ slug: 'skull-crusher', name: 'EZ-Bar Skull Crusher', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['EZ_BAR', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Lower to the forehead/behind the head; keep the elbows still.' }),
  mk({ slug: 'db-skull-crusher', name: 'DB Skull Crusher', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '10-12', cues: 'Neutral grip, lower beside the ears, full stretch.' }),
  mk({ slug: 'floor-skull-crusher', name: 'Floor Skull Crusher', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['BARBELL', 'DUMBBELL'], spinalLoad: 'NONE', defaultRepRange: '8-12', cues: 'Floor limits the stretch — joint-friendly; controlled tempo.' }),
  mk({ slug: 'overhead-rope-extension', name: 'Cable Rope Overhead Triceps Ext', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '12-15', cues: 'Face away, lean in; big stretch on the long head, split the rope.' }),
  mk({ slug: 'overhead-dumbbell-extension', name: 'Overhead DB Extension', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], spinalLoad: 'LOW', defaultRepRange: '10-15', cues: 'One dumbbell overhead; deep stretch, elbows pointed forward.' }),
  mk({ slug: 'tricep-pressdown-rope', name: 'Cable Triceps Pressdown (Rope)', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-15', cues: 'Elbows pinned, split the rope at the bottom, full lockout.' }),
  mk({ slug: 'tricep-pressdown-bar', name: 'Cable Triceps Pressdown (Bar)', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Straight bar; lock out hard, control the return.' }),
  mk({ slug: 'v-bar-pressdown', name: 'V-Bar Pressdown', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Neutral-ish grip; strict lockouts.' }),
  mk({ slug: 'tricep-kickback', name: 'DB Triceps Kickback', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['DUMBBELL'], unilateral: true, spinalLoad: 'LOW', defaultRepRange: '12-20', cues: 'Upper arm parallel and still; extend to a hard squeeze.' }),
  mk({ slug: 'cable-tricep-kickback', name: 'Cable Triceps Kickback', primaryMuscle: 'TRICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], unilateral: true, spinalLoad: 'NONE', defaultRepRange: '15-20', cues: 'Constant tension; lock out and hold each rep.' }),

  // ============================== CORE ==============================
  mk({ slug: 'crunch', name: 'Crunch', primaryMuscle: 'ABS', secondaryMuscles: [], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '15-25', cues: 'Curl the ribs to the pelvis; exhale and squeeze.' }),
  mk({ slug: 'cable-crunch', name: 'Cable Crunch', primaryMuscle: 'ABS', secondaryMuscles: [], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-15', cues: 'Kneel, rope by the head, crunch with the abs not the hips.' }),
  mk({ slug: 'plank', name: 'Plank', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '30-60s', cues: 'Rigid line head-to-heel; squeeze glutes and abs.' }),
  mk({ slug: 'hanging-leg-raise', name: 'Hanging Leg Raise', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES', 'FOREARMS'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['PULL_UP_BAR'], spinalLoad: 'LOW', defaultRepRange: '8-15', cues: 'Curl the pelvis up; no swinging, control the lower.' }),
  mk({ slug: 'lying-leg-raise', name: 'Lying Leg Raise', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '10-20', cues: 'Lower back pressed into the floor; controlled raise and lower.' }),
  mk({ slug: 'reverse-crunch', name: 'Reverse Crunch', primaryMuscle: 'ABS', secondaryMuscles: [], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '12-20', cues: 'Curl the hips off the floor; lower-ab emphasis.' }),
  mk({ slug: 'ab-wheel-rollout', name: 'Ab Wheel Rollout', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES'], movementPattern: 'CORE', category: 'COMPOUND', equipment: ['SLIDER', 'BODYWEIGHT'], spinalLoad: 'MODERATE', defaultRepRange: '8-12', cues: 'Brace hard, roll out as far as you control, no lower-back sag.' }),
  mk({ slug: 'bicycle-crunch', name: 'Bicycle Crunch', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '15-25', cues: 'Opposite elbow to knee; slow and controlled, full twist.' }),
  mk({ slug: 'hollow-hold', name: 'Hollow Hold', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '20-45s', cues: 'Lower back glued down, shoulders and legs off the floor.' }),
  mk({ slug: 'pallof-press', name: 'Pallof Press', primaryMuscle: 'OBLIQUES', secondaryMuscles: ['ABS'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['CABLE', 'BAND'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Resist rotation; press straight out and hold.' }),
  mk({ slug: 'russian-twist', name: 'Russian Twist', primaryMuscle: 'OBLIQUES', secondaryMuscles: ['ABS'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['DUMBBELL', 'BODYWEIGHT'], spinalLoad: 'LOW', defaultRepRange: '15-25', cues: 'Rotate from the torso; controlled, not frantic.' }),
  mk({ slug: 'cable-woodchopper', name: 'Cable Woodchopper', primaryMuscle: 'OBLIQUES', secondaryMuscles: ['ABS'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', defaultRepRange: '12-15', cues: 'Pivot the back foot; chop across the body, drive with the core.' }),

  // ============================== EXTRAS / VARIETY ==============================
  mk({ slug: 'kettlebell-swing', name: 'Kettlebell Swing', primaryMuscle: 'GLUTES', secondaryMuscles: ['HAMSTRINGS', 'UPPER_BACK'], movementPattern: 'HINGE', category: 'COMPOUND', equipment: ['KETTLEBELL'], spinalLoad: 'MODERATE', defaultRepRange: '12-20', cues: 'Hike and snap the hips; the float is from the hinge, not the arms.' }),
  mk({ slug: 'farmers-carry', name: 'Farmer’s Carry', primaryMuscle: 'TRAPS', secondaryMuscles: ['FOREARMS', 'ABS'], movementPattern: 'CARRY', category: 'COMPOUND', equipment: ['DUMBBELL', 'KETTLEBELL'], spinalLoad: 'MODERATE', defaultRepRange: '30-40m', cues: 'Tall and braced; crush the handles, walk smooth.' }),
  mk({ slug: 'incline-cable-curl', name: 'Incline Cable Curl', primaryMuscle: 'BICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE', 'BENCH'], spinalLoad: 'NONE', defaultRepRange: '12-15', cues: 'Recline on a bench facing the stack; long-head stretch with tension.' }),
  mk({ slug: 'rope-hammer-curl', name: 'Cable Rope Hammer Curl', primaryMuscle: 'BICEPS', secondaryMuscles: ['FOREARMS'], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'NONE', defaultRepRange: '12-15', cues: 'Neutral rope; squeeze the brachialis at the top.' }),
  mk({ slug: 'machine-preacher-curl', name: 'Machine Preacher Curl', primaryMuscle: 'BICEPS', secondaryMuscles: [], movementPattern: 'ISOLATION', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', defaultRepRange: '10-15', cues: 'Fixed arc; control the stretch, full squeeze.' }),
  mk({ slug: 'machine-rear-delt-row', name: 'Machine Rear-Delt Row', primaryMuscle: 'REAR_DELTS', secondaryMuscles: ['UPPER_BACK'], movementPattern: 'HORIZONTAL_PULL', category: 'ISOLATION', equipment: ['MACHINE'], spinalLoad: 'NONE', isBackSafe: true, defaultRepRange: '12-20', cues: 'Wide elbows; pull back and squeeze the rear delts.' }),
  mk({ slug: 'incline-smith-press', name: 'Incline Smith Press', primaryMuscle: 'CHEST', secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['SMITH_MACHINE', 'BENCH'], spinalLoad: 'LOW', defaultRepRange: '8-12', cues: 'Upper-chest bias on a fixed path; controlled stretch.' }),
  mk({ slug: 'kneeling-cable-crunch', name: 'Kneeling Cable Crunch', primaryMuscle: 'ABS', secondaryMuscles: ['OBLIQUES'], movementPattern: 'CORE', category: 'ISOLATION', equipment: ['CABLE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '12-20', cues: 'Round the spine over the hips; abs do the work, not the arms.' }),
  mk({ slug: 'banded-pushup', name: 'Banded Push-Up', primaryMuscle: 'CHEST', secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'], movementPattern: 'HORIZONTAL_PUSH', category: 'COMPOUND', equipment: ['BAND', 'BODYWEIGHT'], spinalLoad: 'NONE', defaultRepRange: '10-20', cues: 'Band across the back adds tension at lockout; rigid plank.' }),
  mk({ slug: 'goblet-curl-squat', name: 'Heel-Elevated Smith Squat', primaryMuscle: 'QUADS', secondaryMuscles: ['GLUTES'], movementPattern: 'SQUAT', category: 'COMPOUND', equipment: ['SMITH_MACHINE'], spinalLoad: 'LOW', isBackSafe: true, defaultRepRange: '8-12', cues: 'Heels raised on the fixed path; deep quad-biased reps.' }),
];

module.exports = { exercises };
